spring:
  application:
    name: image-worker
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      sqs:
        endpoint: ${AWS_SERVICE_URL:http://localhost:4566}
      s3:
        endpoint: ${AWS_SERVICE_URL:http://localhost:4566}
  datasource:
    url: jdbc:postgresql://localhost:5432/thumbnail_db
    username: ${DB_USER:dev_user}
    password: ${DB_PASSWORD:dev_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
aws:
  s3:
    bucket: ${S3_BUCKET_NAME:cloud-native}
  sqs:
    queue-name: ${SQS_QUEUE_NAME:image-processing-queue}
app:
  sqs:
    enabled: true
