# services:
#   localstack:
#     container_name: localstack_main
#     image: localstack/localstack:latest
#     ports:
#       - "127.0.0.1:4566:4566"            # Main Edge Proxy (API Gateway, S3, SQS, etc)
#       - "127.0.0.1:4510-4559:4510-4559"  # Range for external services (like RDS/OpenSearch)
#     environment:
#       # --- Authentication ---
#       - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      
#       # --- Performance & Debugging ---
#       - DEBUG=1                          # Set to 0 once everything is working
#       - DOCKER_HOST=unix:///var/run/docker.sock
      
#       # --- Persistence (The "Safe" Button) ---
#       - PERSISTENCE=1                    # Saves your work to disk
#       - SNAPSHOT_SAVE_STRATEGY=SCHEDULED # Automatically saves every 15 seconds
      
#       # --- Local Environment Setup ---
#       - DEFAULT_REGION=us-east-1
#       - AWS_ACCESS_KEY_ID=test           # Use "test" to stay in the local sandbox
#       - AWS_SECRET_ACCESS_KEY=test
#     volumes:
#       - "./ls_data:/var/lib/localstack"  # This is where your S3 files and DBs live
#       - "/var/run/docker.sock:/var/run/docker.sock" # Allows LocalStack to run Lambdas

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
      DEBUG: ${DEBUG}
      PERSISTENCE: ${PERSISTENCE}
      DEFAULT_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DOCKER_HOST: unix:///var/run/docker.sock
      SNAPSHOT_SAVE_STRATEGY: SCHEDULED
    volumes:
      - "./ls_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # --- PostgreSQL Database ---
  postgres_db:
    container_name: cloud_postgres
    image: postgres:16-alpine
    env_file:
      - ../.env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Persistence for your DB

  # --- pgAdmin (Optional GUI for Database) ---
  # Open http://localhost:5050 in your browser
  # Login: admin@admin.com / admin
  pgadmin:
    container_name: pgadmin_main
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db